"""Init

Revision ID: 1b0161c7f37b
Revises: 
Create Date: 2024-03-10 01:11:09.546894

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b0161c7f37b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('hashed_token', sa.String(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('username')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('files',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('owner_username', sa.Integer(), nullable=True),
    sa.Column('original_filename', sa.String(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('mimetype', sa.String(), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('upload_datetime', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('lifetime', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['owner_username'], ['users.username'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_files_filename'), 'files', ['filename'], unique=False)
    op.create_index(op.f('ix_files_id'), 'files', ['id'], unique=False)
    op.create_index(op.f('ix_files_lifetime'), 'files', ['lifetime'], unique=False)
    op.create_index(op.f('ix_files_mimetype'), 'files', ['mimetype'], unique=False)
    op.create_index(op.f('ix_files_original_filename'), 'files', ['original_filename'], unique=False)
    op.create_index(op.f('ix_files_size'), 'files', ['size'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_files_size'), table_name='files')
    op.drop_index(op.f('ix_files_original_filename'), table_name='files')
    op.drop_index(op.f('ix_files_mimetype'), table_name='files')
    op.drop_index(op.f('ix_files_lifetime'), table_name='files')
    op.drop_index(op.f('ix_files_id'), table_name='files')
    op.drop_index(op.f('ix_files_filename'), table_name='files')
    op.drop_table('files')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
